#!/bin/bash
# Launch / watch / collect the M1 T2 run on Kaggle with the official Kaggle CLI.
# Works from Git Bash (e.g. the VS Code terminal) or WSL. Setup steps: README.md.
#
#   bash push.sh login             sign in through the browser (once)
#   bash push.sh check             confirm the CLI is installed and signed in
#   bash push.sh push              run scripts/run_t2.sh on Kaggle at the current commit
#   bash push.sh push --continue   same, with the previous version's output attached, so
#                                  finished runs are skipped and interrupted ones resume
#   ROOMRECON_RESUME_REFS=N bash push.sh push ...   ask for N resume references (default 2)
#   bash push.sh status            queued / running / complete / error
#   bash push.sh fetch             download the results to ./output/ and check the verdict
#
# The notebook is generated, never edited by hand: it clones this repo at the exact commit
# being pushed and runs scripts/run_t2.sh. All logic lives in the repo, where it is tested.
#
# Optional: KAGGLE_DATASET=<owner>/<slug> attaches a Kaggle dataset holding drjohnson, which
# saves the in-session download. Username: $KAGGLE_USERNAME or a legacy kaggle.json.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../../.." && pwd)"
SLUG=roomrecon-m1-t2
GIT_URL=https://github.com/asw-beep/RoomRecon.git
export PIP_NO_CACHE_DIR=1   # nothing piles up in the pip cache on C:
export PYTHONUTF8=1         # Windows' default codepage cannot encode the Kaggle log (T2 run 1)

# the `kaggle` launcher may not be on PATH with the Microsoft Store Python; call the module then
kg() {
  if command -v kaggle >/dev/null 2>&1; then kaggle "$@"
  else python -c "import sys; from kaggle.cli import main; sys.argv[0]='kaggle'; main()" "$@"; fi
}
python -c "import kaggle" >/dev/null 2>&1 || { echo "Kaggle CLI missing: python -m pip install --no-cache-dir kaggle"; exit 1; }

if [ "${1:-}" = login ]; then       # browser sign-in; needs no username yet
  kg auth login; exit
fi

USER_NAME="${KAGGLE_USERNAME:-}"
CFG="${KAGGLE_CONFIG_DIR:-$HOME/.kaggle}"
if [ -z "$USER_NAME" ] && [ -f "$CFG/kaggle.json" ]; then
  USER_NAME=$(python -c "import json,sys;print(json.load(open(sys.argv[1]))['username'])" "$CFG/kaggle.json")
fi
[ -n "$USER_NAME" ] || { echo "Set your Kaggle username:  export KAGGLE_USERNAME=<name from your kaggle.com profile URL>"; exit 1; }

# Nothing reaches Kaggle that is not committed, on GitHub, and passing the unit tests:
# a GPU session is the most expensive place to find a bug (T2 run 1 lost its outputs to a
# parse error a two-line test catches).
preflight() {
  # Only what the session runs must match the pushed commit; doc edits cannot change a run.
  local run_paths=(scripts configs tests)
  git -C "$REPO" diff --quiet HEAD -- "${run_paths[@]}" \
    || { echo "uncommitted changes under ${run_paths[*]} - commit first"; return 1; }
  [ -z "$(git -C "$REPO" ls-files --others --exclude-standard -- scripts/run_t2.sh scripts/setup_t2.sh \
          scripts/train.py scripts/verify_env.py scripts/gpu.py scripts/t2_verdict.py scripts/fetch_scene.py configs)" ] \
    || { echo "files the session runs are not committed - commit first"; return 1; }
  git -C "$REPO" fetch -q origin
  [ -n "$(git -C "$REPO" branch -r --contains HEAD)" ] \
    || { echo "HEAD $(git -C "$REPO" rev-parse --short HEAD) is not on origin - push it first (Kaggle clones from GitHub)"; return 1; }
  bash -n "$REPO/scripts/run_t2.sh" && bash -n "$REPO/scripts/setup_t2.sh" || return 1
  (cd "$REPO" && python -m unittest discover -s tests -t . -q) || { echo "unit tests fail - not pushing"; return 1; }
}

# notebook <sha> <continue:0|1>: one %%bash cell. %%bash raises on a non-zero exit, so the Kaggle status
# follows run_t2.sh's exit code, which is the gate verdict. The clone goes to /tmp so the
# repo does not end up in the session output.
notebook() {
  python - "$1" "$GIT_URL" "$2" "${ROOMRECON_RESUME_REFS:-}" <<'EOF'
import json, sys
sha, url, cont, refs = sys.argv[1:5]
env = "".join(f"export {k}={v}\n" for k, v in
              [("ROOMRECON_T2_CONTINUE", int(cont))] + ([("ROOMRECON_RESUME_REFS", int(refs))] if refs else []))
src = f"""%%bash
# Generated by scripts/kaggle/m1_t2/push.sh - do not edit. RoomRecon @ {sha}
set -euo pipefail
{env}rm -rf /tmp/RoomRecon
git clone -q {url} /tmp/RoomRecon
git -C /tmp/RoomRecon checkout -q {sha}
bash /tmp/RoomRecon/scripts/run_t2.sh
"""
nb = {"cells": [{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
                 "source": src.splitlines(keepends=True)}],
      "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                   "language_info": {"name": "python"}},
      "nbformat": 4, "nbformat_minor": 5}
print(json.dumps(nb, indent=1))
EOF
}

# metadata <continue:0|1>: the tracked template keeps placeholders; real values go only
# into the temp copy that is pushed.
metadata() {
  python - "$HERE/kernel-metadata.json" "$USER_NAME" "$SLUG" "${KAGGLE_DATASET:-}" "$1" <<'EOF'
import json, sys
path, user, slug, dataset, cont = sys.argv[1:]
m = json.load(open(path))
m["id"] = m["id"].replace("KAGGLE_USERNAME", user)
m["dataset_sources"] = [dataset] if dataset else []
m["kernel_sources"] = [f"{user}/{slug}"] if cont == "1" else []
print(json.dumps(m, indent=2))
EOF
}

# Results only: resume.pt / checkpoints also sit in the session output (for --continue)
# and must not be pulled to E:. The listing is paginated, so ask for the largest page.
# No "/" in the pattern: Git Bash rewrites any argument containing one as a path, turning
# "(^|/)" into "(^|C:/Program Files/Git/)" and every "\." into "/.", so nothing matched.
RESULTS='^(verdict\.json|stages\.jsonl|m1_t2_artifact\.tar\.gz)$|\.log$'

case "${1:-}" in
check)
  echo "Kaggle user: $USER_NAME"
  kg kernels list --mine --page-size 5 && echo "OK: signed in and the API answers"
  ;;
push)
  CONT=0; [ "${2:-}" = --continue ] && CONT=1
  preflight
  SHA=$(git -C "$REPO" rev-parse HEAD)
  TMP=$(mktemp -d)
  notebook "$SHA" $CONT > "$TMP/$SLUG.ipynb"
  metadata $CONT > "$TMP/kernel-metadata.json"
  kg kernels push -p "$TMP"
  rm -rf "$TMP"
  echo "Started at ${SHA:0:7}$([ $CONT = 1 ] && echo ', continuing from the previous version')."
  echo "Watch: bash push.sh status  |  web: https://www.kaggle.com/code/$USER_NAME/$SLUG"
  ;;
status) kg kernels status "$USER_NAME/$SLUG" ;;
fetch)
  # outputs go next to this script on E: (git-ignored), never to a C: download folder
  rm -rf "$HERE/output"; mkdir -p "$HERE/output"
  kg kernels output "$USER_NAME/$SLUG" -p "$HERE/output" --force \
    --file-pattern "$RESULTS" --page-size 200
  # A download that "succeeds" with empty or missing files is a failure (T2 run 1).
  python - "$HERE/output" <<'EOF'
import json, sys
from pathlib import Path
out = Path(sys.argv[1])
problems = [f"{p.relative_to(out)} is empty" for p in out.rglob("*") if p.is_file() and p.stat().st_size == 0]
art = out / "m1_t2_artifact.tar.gz"
if not art.is_file():
    problems.append("m1_t2_artifact.tar.gz missing")
try:
    v = json.loads((out / "verdict.json").read_text())
except (OSError, ValueError) as exc:
    v, problems = None, problems + [f"verdict.json unusable: {exc}"]
if v:
    print(f"verdict: {'PASSED' if v['passed'] else 'FAILED'}")
    for c in v["checks"]:
        print(f"  {'PASS' if c['ok'] else 'FAIL'}  {c['check']:<50} {c['detail']}")
    if v.get("resume_comparison"):
        print(f"  info  {v['resume_comparison']}")
for p in problems:
    print(f"FETCH PROBLEM: {p}")
sys.exit(1 if problems or not (v and v["passed"]) else 0)
EOF
  ;;
*) echo "usage: bash push.sh login|check|push [--continue]|status|fetch"; exit 2 ;;
esac
